### ISSUE TITLE
Installation Experience + Not working

### ISSUE THREAD

**Issue by B4rc1** [IIFabixn/CSG_Toolkit#1]
Hi, I really like the idea of this addon, however if i installed it from the asset library it installes this addon into the root of my project (the file conflict is `LICENSE.md`:
![grafik](https://github.com/IIFabixn/CSG_Toolkit/assets/10383737/c7461de4-fe70-4491-ad02-c17f19280424)

Which causes scripts to fail because they expect all the content in `addons/csg_toolkit`:
```
res://scripts/csg_toolkit_bar.gd:30 - Parse Error: Preload file "res://addons/csg_toolkit/scenes/config_window.tscn" does not exist.
```

If i manually create the directory structure that is expected and install the addon there, i get these errors:
```
 scene/resources/resource_format_text.cpp:284 - res://addons/csg_toolkit/scenes/config_window.tscn:14 - Parse Error: 
  Failed loading resource: res://addons/csg_toolkit/scenes/config_window.tscn. Make sure resources have been imported by opening the project in the editor at least once.
```

If i try to open ` res://addons/csg_toolkit/scenes/config_window.tscn` in the editor it tells me `Scene file 'config_window.tscn appears to be invalid/corrupted`.

Specs:
```
OS: Windows 11
Godot: Godot Engine v4.2.2.stable.official.15073afe3
```

**Comment by IIFabixn** [comment]
Hey, thank you for your feedback. I’ll look into it right away.

**Comment by IIFabixn** [comment]
I can confirm that there's an issue with `config_window.tscn.`
Thank you for noting that manually creating the required folder structure resolves the initial Parse Error.

**Comment by IIFabixn** [comment]
I was able to reproduce the issue.
After creating a new blank project, installing the current version of the plugin from the asset library, and manually creating the folder structure, I encountered the same error message. <b>However, after reloading the project, the issue no longer persisted.</b>
Could you please try the same steps and let me know if the bug still exists for you?

**Comment by B4rc1** [comment]
It still persits for me even after i restart godot and reload the project.

**Comment by B4rc1** [comment]
ok but i get other behaviour if i try to open the scene after restarting the project, i get the following error:
![grafik](https://github.com/IIFabixn/CSG_Toolkit/assets/10383737/24e824a4-6631-4329-bd5d-ade5159b45b8)

I verified that the script exists in that path...
If i press open anyways i get the same scene corrupt error as before.
If i press fix dependecies, godot warns me that the scene is open, i choose the script, same error...

After doing that once I only get the scene corrupted error from then on...

Very strange!

**Comment by B4rc1** [comment]
oh okay so after reloading the editor several times because of testing i noticed no more errors on startup and now i cant reproduce the original bug after restarting..

Would you mind pushing a fix for the installation and I try again with my setup to see if this works on my setup?

**Comment by IIFabixn** [comment]
I'm pleased to hear the issue is resolved. Enjoy using the toolkit!
I'll work on implementing a fix for the setup process.

**Comment by IIFabixn** [comment]
Fix just got published to the godot asset store. 🚀 
Let me know if that helped. 🤞 

https://godotengine.org/asset-library/asset/3057

**Comment by B4rc1** [comment]
Well after this fix the addon installs correctly. (altough it still installs `LICENSE` and `readme.md` into the project root)

I get the same error as before about the scene beeing invalid. After restarting the editor, i get no error but the addon is disabled and I have to manually renable it in the project settings. (presumably because it produced an error after installing?) After that it works.

I think this should still be fixed.

**Comment by IIFabixn** [comment]
Regarding the LICENSE and readme.md conflicts, there's not much I can do, as modifying them might affect the proper display of my repository. However, these conflicts should not override your files since conflicting files will not be installed. For now, the best approach might be to reload the project after installation. 🤔

**Comment by B4rc1** [comment]
yeah but also manually enabling the plugin. If you are unable to fix it, at least mention it in the readme as it might confuse new users as to why the plugin is not working.
