### ISSUE TITLE
Testing for compatibility with new csg

### ISSUE THREAD

**Issue by fire** [IIFabixn/CSG_Toolkit#3]
Hi, 

I'm working on a better mesh boolean pull request for godot engine. 

Would you like to test if it improves your workflow?

https://github.com/godotengine/godot/pull/94321

**Comment by IIFabixn** [comment]
Hey, Thanks for your Comment. 
Sure, I'll take a look at it and test it as soon as I got some spare time.

**Comment by fire** [comment]
Csg is now in preview versions of Godot Engine 4.4. Critical bug was found a fixed with uvs.

**Comment by IIFabixn** [comment]
@fire Hi, apologies for the late response. I’ve reviewed your changes and tested them in the version you mentioned. Everything is working perfectly, and I haven’t encountered any issues so far. Great job!
